backend:
  name: github
  repo: SMIEJMSJ/marojersey-store
  branch: main

site_url: https://glittery-melomakarona-59e439.netlify.app
media_folder: "images"
public_folder: "/images"

collections:
  - name: "products"
    label: "Products"
    folder: "products"
    create: true
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Price", name: "price", widget: "number" }
      - { label: "Image", name: "image", widget: "image" }
      - { label: "Description", name: "body", widget: "markdown" }